version: 2.2.3

services:
  secret_agent:
    image: worldofelisa/laravel-php:8.0-fpm
#    build:
#      context: ./docker/php
#      dockerfile: Dockerfile
    ports:
      - 9004:9000
    volumes:
      - ./app/:/var/www/
    networks:
      - web-network
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
    networks:
      - web-network

networks:
  web-network:
    driver: bridge